name: test

on: [ push, pull_request ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: ["2.11.x", "2.12.x", "2.13.x"]

    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
        check-latest: true
    - name: Run tests
      run: sbt ++${{ matrix.scala }} test
